TrabalhoWeb/carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho'

urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>/', views.remover_do_carrinho, name='remover_do_carrinho'),
]

TrabalhoWeb/lojavirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('produtos/', include('produtos.urls', namespace='produtos')),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrabalhoWeb/main/urls.py
from django.urls import path
from .views import index, sobre, contato

urlpatterns = [
    path('', index, name='index'),
    path('sobre/', sobre, name='sobre'),
    path('contato/', contato, name='contato')
]

TrabalhoWeb/pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('criar/', views.criar_pedido, name='criar_pedido')
]

TrabalhoWeb/produtos/urls.py
from django.urls import path
from .views import listar_produtos, detalhar_produto

app_name = 'produtos'

urlpatterns = [
    path('<str:id_produto>/<slug_produto>/', detalhar_produto, name='detalhes_produto'),
    path('<slug_categoria>/', listar_produtos, name='listar_produtos_por_categoria'),
    path('', listar_produtos, name='listar_produtos'),
]

TrabalhoWeb/carrinho/models.py
from django.db import models

# Create your models here.

TrabalhoWeb/carrinho/forms.py
from django import forms

OPCOES_QUANTIDADE_PRODUTO = []

for i in range(1, 11):
    OPCOES_QUANTIDADE_PRODUTO.append((i, str(i)))

class FormAdicionarProdutoAoCarrinho(forms.Form):

    quantidade = forms.TypedChoiceField(
        choices=OPCOES_QUANTIDADE_PRODUTO, coerce=int)

    atualizar = forms.BooleanField(required=False, widget=forms.HiddenInput)

TrabalhoWeb/carrinho/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from produtos.models import Produto
from .carrinho import Carrinho
from .forms import FormAdicionarProdutoAoCarrinho

@require_POST
def adicionar_ao_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    form = FormAdicionarProdutoAoCarrinho(request.POST)
    if form.is_valid():
        dados = form.cleaned_data
        carrinho.adicionar(
            produto=produto,
            quantidade=dados['quantidade'],
            atualizar_quantidade=dados['atualizar'])
    return redirect('carrinho:detalhes_carrinho')

def remover_do_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    carrinho.remover(produto)
    return redirect('carrinho:detalhes_carrinho')

def detalhes_carrinho(request):
    carrinho = Carrinho(request)
    for item in carrinho:
        item['formulario_adicionar_produto_ao_carrinho'] = \
            FormAdicionarProdutoAoCarrinho(
                initial={'quantidade': item['quantidade'], 'atualizar': True})
    return render(request, 'carrinho/detalhes_carrinho.html', {'carrinho': carrinho})

TrabalhoWeb/templates/carrinho/detalhes_carrinho.html
{% extends "base.html" %}
{% block conteudo %}
    <div class="container-2">
        {% if carrinho|length == 0 %}
        <div class="cart-1">
            <h2 class="cart-1-title">Seu Carrinho está vazio!</h2>
    
            <div class="cart-gifs">
                <img src="/static/gif/confused-John-Travolta.gif" class="adj-gif">
                <img src="/static/gif/Jack-Sparrow.gif" class="center-gif">
                <img src="/static/gif/black-dude-crying.gif" class="adj-gif">
            </div>
    
            <button class="general-buttons">
                <a href="{% url 'produtos:listar_produtos' %}">Ir para loja</a>
            </button>
        </div>
        {% else %}
        <div class="cart-2">
            <h2 class="cart-title-2">Seu Carrinho de Compras:</h2>
            <table class="cart-table">
                <thead class="cart-thead">
                    <tr>
                        <th class="cart-thead-item product-previa"></th>
                        <th class="cart-thead-item">Produto</th>
                        <th class="cart-thead-item">Quantidade</th>
                        <th class="cart-thead-item">Remover</th>
                        <th class="cart-thead-item">Preço unitário</th>
                        <th class="cart-thead-item">Subtotal</th>
                    </tr>
                </thead>

                <tbody class="cart-tbody">
                    {% for item in carrinho %}
                    {% with produto=item.produto %}
                    <tr>
                        <td class="product-previa"><img src="{{ produto.imagem.url }}" alt="{{ produto.nome }}" class="cart-product-image"></td>

                        <td class="cart-tbody-item" id="product-name">{{ produto.nome }}</td>

                        <td class="cart-tbody-item">
                            <form action="{% url 'carrinho:adicionar_ao_carrinho' produto.id %}" method = "post">
                            {% csrf_token %}
                                {{ item.formulario_adicionar_produto_ao_carrinho.quantidade }}
                                {{ item.formulario_adicionar_produto_ao_carrinho.atualizar }}
                                <input type="submit" value="Atualizar">
                            </form>
                        </td>

                        <td class="cart-tbody-item">
                            <a href="{% url 'carrinho:remover_do_carrinho' produto.id %}" id="cart-remove">Remover</a>
                        </td>

                        <td class="cart-tbody-item">R$ {{ item.preco }}</td>
                        
                        <td class="cart-tbody-item">R$ {{ item.subtotal }}</td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                </tbody>

                <tfoot>
                    <tr>
                        <td colspan="6">Total: R$ {{ carrinho.get_total_geral }}</td>
                    </tr>
                </tfoot>
            </table>

            <div class="cart-buttons">
                <div class="cart-buttons-config">  
                    <a href="{% url 'produtos:listar_produtos' %}">
                        <button class="general-buttons">Continuar comprando</button>
                    </a>
                </div>
                    
                <div class="cart-buttons-config">
                    <a href="{% url 'pedidos:criar_pedido' %}">
                        <button class="general-buttons">Finalizar</button>
                    </a>    
                </div>
            </div>
        </div>  
        {% endif %}
    </div>
{% endblock %}